name: Robot Framework CI
 
on:
  push
 
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
 
    steps:
    - name: Clonar arquivos do repositório
      uses: actions/checkout@v4
 
    - name: Configurar Python  
      uses: actions/setup-python@v4
      with:
          python-version: 3.x
 
    - name: Instalação das dependências
      run: |
        pip install --upgrade robotframework
        pip install --upgrade robotframework-faker
        pip install robotframework-requests
        pip install --upgrade setuptools


    - name: Executar testes do Robot Framework  
      run: 
        robot -d log tests
 
    - name: Salvar o resultado dos testes
      if: ${{ always() }}  
      uses: actions/upload-artifact@v4
      with:
        name: robot-log
        path: ./log