name: Robot Framework CI
 
on:
  push
 
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
 
    steps:
    - name: Clonar arquivos do repositório
      uses: actions/checkout@v3
 
    - name: Configurar Python  
      uses: actions/setup-python@v3
      with:
          python-version: 3.x
 
    - name: Instalação das dependências
      run: |
        pip install --upgrade robotframework
        pip install --upgrade robotframework-faker
 
    - name: Executar testes do Robot Framework  
      run: |
        robot -d results tests
 
    - name: Salvar o resultado dos testes
      if: ${{ always() }}  
      uses: actions/upload-artifact@v3
      with:
        name: robot-results
        path: ./results